### ISSUE TITLE
Replace file doesn't work, shows "Not found" error

### ISSUE THREAD

**Issue by halkyon** [symbiote/silverstripe-versionedfiles#14]
Can't replace an uploaded file with another, it shows a "Not found" error.

![replace_file_not_found](https://f.cloud.github.com/assets/138450/505813/f3f4d134-bd38-11e2-85b2-f23b10da7435.jpg)

SilverStripe 3.1.x-dev clean installer
versionedfiles master

**Comment by robbieaverill** [comment]
No longer an issue, I can replace files correctly.
