### ISSUE TITLE
Replace file panel styling broken

### ISSUE THREAD

**Issue by halkyon** [symbiote/silverstripe-versionedfiles#15]
Looks a bit broken, the "Upload" panel for normal file uploads looks fine however.
Maybe this is missing some classes or something?

![replace_file_styling_broken](https://f.cloud.github.com/assets/138450/505819/1bea2bd0-bd39-11e2-902d-adf2782ae508.jpg)

SilverStripe 3.1.x-dev
versionedfiles master

**Comment by robbieaverill** [comment]
Looks good on CWP 1.9.x-dev, no longer an issue:

![image](https://user-images.githubusercontent.com/5170590/57493386-c56a5400-7318-11e9-93e6-d3e280458ea3.png)
