### ISSUE TITLE
Renaming a file doesn't get a new revision in history

### ISSUE THREAD

**Issue by halkyon** [symbiote/silverstripe-versionedfiles#16]
If I rename a file, then save it, there's no change for this in the file history.

I assume there's only currently a new revision created when you replace the file itself, but not it's filename or metadata.

**Comment by robbieaverill** [comment]
This is still true in CWP 1.9.x-dev

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
