### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by twodayslate** [symbiote/silverstripe-versionedfiles#18]
Warning: Missing argument 2 for Object::add_extension(), called in /var/www/html/ss/versionedfiles/_config.php on line 6 and defined in /var/www/html/ss/framework/core/Object.php on line 453 Notice: Undefined variable: extension in /var/www/html/ss/framework/core/Object.php on line 454 Fatal error: Object::add_extension() - Can't find extension class for "" in /var/www/html/ss/framework/core/Object.php on line 460

Under v3.0.5

No error under v3.1b3 but I don't see the module actually working or existing

**Comment by robbieaverill** [comment]
In the latest SilverStripe 3.x the second argument for `add_extension` is optional, so this is not longer an issue.
