### ISSUE TITLE
Display warning if file already exists

### ISSUE THREAD

**Issue by smagnusson** [symbiote/silverstripe-versionedfiles#3]
"Requirement: The product shall display a warning to a content author if a document uploaded by the content author has been uploaded already and provide the option to overwrite an already-uploaded document with a newer version"

Right now you can upload a brand new file, or you can upload an update to an existing file. This ticket is discussing the issue of someone creating a brand new file, and it detecting that the user might actually want to update an existing file.

Example dialogue:

"A filename called silverstripe-is-cool.png already exists in the folder /assets/cool-files/. Would you like to overwrite this file or create a duplicate named silverstripe-is-cool-2.png?
[Overwrite] [Duplicate]"

Minimally, this occurs in the file assets area, but preferably the check and dialogue also occurs in the image inserter within TinyMCE, and I'm not sure of the appropriate solution for custom file-upload fields.

Matching is done on exact-filename basis only, no need to get fancier in my opinion.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
