### ISSUE TITLE
Viewing historic image shows current not past thumbnail.

### ISSUE THREAD

**Issue by camfindlay** [symbiote/silverstripe-versionedfiles#39]
When viewing an image that has many historic versions, viewing an individual version shows a thumbnail of the current image version and not the historic image.

This makes it difficult to go back and find old images visually to revert to.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
